### PR TITLE
Update Node.js and npm

### PR DESCRIPTION
**Pull request by akito19**
Updated Node.js to 12.3.1 from 11.5.0. Node.js 11.x has been
end-of-life 2 days ago.

Node 12.x release pages are as follows:

* https://nodejs.org/en/blog/release/v12.3.1/
* https://nodejs.org/en/blog/release/v12.3.0/
* https://nodejs.org/en/blog/release/v12.2.0/
* https://nodejs.org/en/blog/release/v12.1.0/
* https://nodejs.org/en/blog/release/v12.0.0/

Following links are npm ones:

* https://github.com/npm/cli/releases/tag/v6.9.0
* https://github.com/npm/cli/releases/tag/v6.8.0
* https://github.com/npm/cli/releases/tag/v6.7.0
* https://github.com/npm/cli/releases/tag/v6.6.0

npm updates did not include breaking changes, thus the change put
together in Node.js update commit.

### CODE REVIEW

**Comment by ybiquitous** [comment]
[question] If users have broken packages in Node 12, for example `npm install` will fail?
https://github.com/nodejs/node/issues/25060

**Comment by akito19** [comment]
`npm install` will be failed in that situation. However, I believe that the problem shouldn't be the release blocker because Node 11 has already been ended of support and we won't update Node version if we wait for that all packages support Node 12.

In addition, we can revert devon_rex version if we in trouble in Node 12's images since we manage devon_rex with versioning. What do you think about?

**Comment by ybiquitous** [comment]
If we want to avoid the EOL version in the current situation, we have to use Node 10 LTS instead of Node 11.
Because Node 12 can break users analysis or packages installation yet.

Also, the `devon_rex` image is a base image, so it will take more time to revert. I think we should avoid the revert as possible.

But, for analyzers without `npm install`, I think updating to Node 12 is OK.

**Comment by akito19** [comment]
Hmm, should we downgrade Node version against our decision? 🤔 
https://3.basecamp.com/3787557/buckets/4315169/todos/1463716130

We only have to fix devon_rex version each runner uses when some errors occur, which it means not to need to revert devon_rex_npm itself.

**Comment by ybiquitous** [comment]
> Hmm, should we downgrade Node version against our decision? 🤔

No. Because the downgrade has some cost, I think better we may wait and see for a while. It's risky to update now.

> We only have to fix devon_rex version each runner uses when some errors occur, which it means not to need to revert devon_rex_npm itself.

Yes, but changing code, waiting for CIs and deploying will take more time. During it, analyses will break.

**Comment by akito19** [comment]
Are we prefer to keep Node version for a while? However, I'd like to decide the date that we wait for because we won't update Node version if we wait until almost packages support Node 12.

I'll update Node.js after the updatable date unless severe security problem happens.

**Comment by ybiquitous** [comment]
Of course, the EOL version can cause security issues in the future. This problem is a trade-off.

- Break analyses due to unsupported dependent packages.
- Case security issues due to the EOL Node 11.

Actually, I think we can't decide "the updatable date" now, because very famous packages such as [`graceful-fs`](https://www.npmjs.com/package/graceful-fs) have no support of Node 12.
(such packages are dependent by many packages, for example, `gracefull-fs` has **1,738** dependent packages)

IMO, we should wait for the update to Node 12 until Node 11 will cause an important security issue or such packages will support Node 12.
On **2019-10-22** Node 12 will become the active LTS version, so I think the date is a deadline.
See <https://nodejs.org/en/about/releases/>.

I think the risk to break user analyses is bigger now.

**Comment by akito19** [comment]
Ok, I make the PR rest for a while, yet if severe problems emerge, I'll update Node unconditionally.

**Pull request closed without merging**
